### ISSUE TITLE
Performance Audit 2017: New Loader Snippet without IFRAME

### ISSUE THREAD

**Issue by nicjansma** [akamai/boomerang#164]
The Boomerang Loader Snippet has a cost, more than a regular `<script>` tag would.  Here's a breakdown on machines I've tested:

![image](https://user-images.githubusercontent.com/1004649/34300834-0055ce2c-e6f8-11e7-8c69-20ccffa85e3a.png)

We should investigate alternative ways of loading Boomerang in an asynchronous, non-blocking manner.

@bluesmoon and others have been investigating this.

**Comment by yoavweiss** [comment]
A preload-based snippet could look something like: http://jsbin.com/sobacusizu/1/edit?html,console,output

**Comment by nicjansma** [comment]
After extensive [research and testing](https://calendar.perfplanet.com/2018/a-csp-compliant-non-blocking-script-loader/), we're released a significant update to the mPulse Loader Snippet that addresses a lot of the performance concerns and several SEO concerns with the previous snippet.  Going forward, we are recommending use of the new "Version 12" of the mPulse Loader Snippet, documented here: https://akamai.github.io/boomerang/tutorial-loader-snippet.html

Version 12 is now CSP-compliant and avoids IFRAMEs most modern browsers.

This snippet avoids creating an IFRAME in any browser that supports [Preload](https://caniuse.com/#feat=link-rel-preload).

This change is in https://github.com/akamai/boomerang/commit/33371c30986f3c9b5c594be55781cd1f14c85c43
