### ISSUE TITLE
Performance Audit 2017: Beacon: ResourceTiming Compression

### ISSUE THREAD

**Issue by nicjansma** [akamai/boomerang#174]
`ResourceTiming` is currently the most expensive plugin as far as JavaScript CPU time and beacon size for larger sites.

![image](https://user-images.githubusercontent.com/1004649/34304265-042b4b4e-e707-11e7-98e8-1493a5ade874.png)

Depending on the site and device, compressing the ResourceTiming entries could take 20-100 milliseconds or more.

We should investigate ways of reducing this cost.  Some ideas:

* Before compressing the entries, we must iterate over all of the frames in the page to gather all entries.  We could use the `PerformanceObserver` in some (or all) frames to get notified of new entries, instead of crawling for them
* The `optimizeTrie` is the most expensive operation, where it iterates over each character in every URL.  We could look into forming a non-perfect Trie by grouping every 10 characters together, or something

**Comment by bluesmoon** [comment]
For optimizeTrie, we could also just split on `[./?&=]` and use those as groups.  Also, reversing the hostname should be built in.

We should also see if we can move the optimization over to a WebWorker and use postMessage to send the resulting string back to the main thread.

**Comment by nicjansma** [comment]
We have a fix in review (Akamai repo), which splits the URL at the path separator `/` instead of by every character in `convertToTrie()`.

Summary of the benefits:

* These optimizations are more important on larger sites (i.e. 100+ URLs)
* On sites where the ResourceTiming optimization was taking > 100ms (on desktop CPUs), changing to splitting at `/` reduced CPU time to ~25ms at only a 4% growth in data (`restiming`) size.
* On sites taking 25-35ms, changing to `/` reduced CPU time to ~10ms at 2-3% data growth

**Comment by nicjansma** [comment]
Merged in as https://github.com/akamai/boomerang/commit/7834819ec087948ae789d5a7306fb83f3c52e4dc
