### ISSUE TITLE
SPA - Event listeners stacking up for long living dynamic elements

### ISSUE THREAD

**Issue by adrienbu** [akamai/boomerang#190]
In the context of a SPA, when a specific DOM element is being dynamically loaded during soft page loads, auto-xhr plugins add new event listeners (on `load` and `error` events) at each load but never clean up old event listener. This does not introduce any bug because in the `load_cb` function being called, we check if we already have an end time for this ressource. However this can lead to performance issues for long living elements.

I've created this plunker sample where you can reproduce this issue. the `new.boomerang.js` file has been created from `soasta-2018` with following plugins: rt, restiming, auto-xhr, spa, angular, navtiming.
https://plnkr.co/DkFJlOMBP1TCC8Zzppl8
Once you've run the sample, open debugging console and put a breakpoint inside the `MutationHandler.prototype.load_cb` function. When you navigate between the 2 links in the page, you will see the function being called multiple times for the same element (called one time more at every change)

I've investigated a bit and the issue comes IMO from the function `MutationHandler.prototype.wait_for_node`  and especially those lines
```
node.addEventListener("load", function(ev) { self.load_cb(ev, resourceNum); });
node.addEventListener("error", function(ev) { self.load_cb(ev, resourceNum); });
```
When the node is long living, we add up event listeners without ever cleaning them up.

**Comment by nicjansma** [comment]
Wow, now that's what I call a bug report!  Repro site and everything -- thank you!

Looks like we might be able to work around this by passing in `{ once: true }`:

```
node.addEventListener("load", function(ev) { self.load_cb(ev, resourceNum); }, { once: true });
node.addEventListener("error", function(ev) { self.load_cb(ev, resourceNum); }, { once: true });
```

We'll build some tests around this and get it backported soon.

Thanks @adrienbu !

**Comment by adrienbu** [comment]
You're welcome 😀 
Thanks for the good work.

**Comment by nicjansma** [comment]
Fixed in https://github.com/akamai/boomerang/commit/9cb0d48b90c210a1567a58b047519611899a6329
