### ISSUE TITLE
Navigation Timing Plugin sends twice per page

### ISSUE THREAD

**Issue by neurolabs** [akamai/boomerang#195]
When I include the navigation timing plugin, it sends on pageReady as well as on unload. I expect it to send a complete set of data once.

The data at pageReady is complete, so for my use case, it would suffice to not set this.complete to false in the function clear.

**Comment by bluesmoon** [comment]
While it's true that in most cases when pageReady fires, navigation timing data should be complete, there is an edge case where if pageReady fires before onload (ie, the developer fires it manually), then NT data won't be complete, so sending it later on unload is a good idea.

I think we could do something like only resend the data if it is incomplete on the first beacon.

**Comment by neurolabs** [comment]
If you have an idea on how to achieve that, I am willing to implement a PR.

**Comment by bluesmoon** [comment]
I think you need to look at `impl.clear` in navtiming.js, and tie it together with `impl.done` where you need to check if all parameters were set.

**Comment by neurolabs** [comment]
Just so you know, not all browsers support XHR on unload: https://bugs.webkit.org/show_bug.cgi?id=26817
That's the reason I am currently working on our integration.

Regarding an implementation: I am unsure how I can deduce that a value has not been properly sent before. My approach would be to store sent values, and on a second data call, only add those values that have changed since the last send. What do you think?

**Comment by bluesmoon** [comment]
I think you just need a flag.  If `loadEventEnd` is non-zero in the `done` method, then the flag is set to `true`, if not, it is set to `false`.  If the flag is `false`, then we will resend the data.

I think we will use `sendBeacon` if available and fall back to XHR if not.  It looks like Safari on El Capitan/Sierra will probably need to fall back to XHR.

**Comment by judwhite** [comment]
@neurolabs Was this fixed for you in #197?
