### ISSUE TITLE
trying navigator.sendBeacon() first makes all sendBeacon calls use POST

### ISSUE THREAD

**Issue by bcollins17** [akamai/boomerang#199]
As long as navigator.sendBeacon() is available, boomerang.js tries to use it[1]. Since the method used by navigator.sendBeacon() is always POST[2] , and the return value is true if the data is merely queued to send[3], the boomerang agent is sending beacon data as a post and then returning, even if the beacon_type is specified as "GET", and the beacon send actually fails.

[1] https://github.com/SOASTA/boomerang/blob/master/boomerang.js#L3285-L3287
[2] https://w3c.github.io/beacon/ Section 3.2, Step 7, under "method"
[3] https://w3c.github.io/beacon/ Section 3.1, under "Return Value"

**Comment by bcollins17** [comment]
Mostly it just seems like the return for nav.sendBeacon makes it so that setting the beacon_type to GET is largely useless, and should be removed for clarity's sake.  Even though I am going to make it so my server can accept POST as well, it took quite a while of troubleshooting to figure out that nav.sendBeacon always returning true is why it's failing. 

Ideally we should find a way to get an actual verification on if nav.sendBeacon() succeeded, instead of just checking that the action has been queued. Barring that, it seems like trying to GET should happen first if beacon_type is explicitly set to GET.

**Comment by bluesmoon** [comment]
There's no way to tell if the beacon was actually sent since it might happen after the window has closed and the JavaScript context is cleared.  If it happens while JavaScript is still executing, then it will show up in ResourceTiming with initiatorType set to beacon.

We know that if sendBeacon returns true, then the browser guarantees that the beacon will be sent unless it receives something like a `kill -9` or the network goes away before it can complete that task. Returning false means that the browser knows for sure that it won't be able to send the beacon this way.

**Comment by nicjansma** [comment]
Wish I could `@here` to ask everyone who's using Boomerang if they have a `GET`-only server :)

I think we should either:
* Keep `beacon_type`, with a big warning that if set to `GET` and the size is > 2k characters, no data will be sent, and only use Image/XHR
* Remove `beacon_type` and just document that beacons could come in as GET or POST requests.

**Comment by tcgerhard** [comment]
We currently have a GET-only server :-(   
We ran into this issue this week after a test build of the latest (we're running a quite old build, so don't know when this was introduced).   Spent some time making the same discovery as the OP on this issue; the doc doesn't reflect what actually happens.
Server changes move with a different cadence from frond end, so it'll be a little while until we can resume testing.

**Comment by nicjansma** [comment]
Thanks for the feedback @tcgerhard!

Do you not have the `restiming` plugin enabled?  (that's the main driver of >2kb beacons).

Would (1) be best for you then? i.e. never use `navigator.sendBeacon()`?

**Comment by tcgerhard** [comment]
We don't have the restiming plugin enabled currently.

I'm a fan of navigator.sendBeacon(), but would prefer an option to not use it while we're updating our backend.   Realistically, we'll get the backend updated before you'd be likely to release an update, so it's not a big deal for us, but there may be others surprised by the behavior like we were.

**Comment by nicjansma** [comment]
Fixed via 1e2992e47c84ebff2f2cf073a1cb013b168bd4a7
