### ISSUE TITLE
Get iOS device hardware from WebGL [via andydavies]

### ISSUE THREAD

**Issue by bluesmoon** [akamai/boomerang#200]
@andydavies on the Web Performance slack asked if anyone was collecting iOS device hardware details and provided this snippet:
```
{
var webgl = {};

try {

    var c = document.createElement('canvas');
    var g = c.getContext('webgl');
    var d = g.getExtension('WEBGL_debug_renderer_info');

    webgl = {
        'vendor': g.getParameter(d.UNMASKED_VENDOR_WEBGL),
        'renderer':  g.getParameter(d.UNMASKED_RENDERER_WEBGL)
    }
}
catch(e) {
    console.log(e);
}

console.log(webgl);
}
```

He says he can write up a plugin in a few weeks.

**Comment by msolnit** [comment]
Interesting.  What's the performance impact of spinning up a WebGL context?

**Comment by bluesmoon** [comment]
We generally feature detect. If it exists, we collect it, if not, we don't. Doesn't matter which browser/device. I don't believe there are performance issues with just getting the context. It's rendering that uses the GPU.

**Comment by rpierce99** [comment]
On my laptop it takes about 14ms https://jsperf.com/webgl-context/1

**Comment by rpierce99** [comment]
Oddly my iPhone performs significantly better, 300/sec or ~3ms

**Comment by bluesmoon** [comment]
Here's an incremental test, it does show that getting webgl context is the bottleneck: https://jsperf.com/boomr-webgl

**Comment by bluesmoon** [comment]
Well, the good thing is that it only needs to be run once, the bad thing is that 14ms is very close to the  16ms that we have for a single frame.

**Comment by nicjansma** [comment]
Maybe if we could do this in a worker?  Otherwise the cost seems pretty high.

**Comment by andydavies** [comment]
I'm slowly running some tests on this - currently sending it to GA - but was also planning to use the AWS device lab to test against a range of devices understand the cost and iOS version limitations.

**Comment by nicjansma** [comment]
@andydavies Any additional results or thoughts on the cost?

**Comment by andydavies** [comment]
No, not finished the testing yet - 'real work' got in the way, also have the horrible feeling Apple are going to remove access to it

**Comment by nicjansma** [comment]
Based on the cost and iOS-specific nature of this, I'd be inclined to not gather this info.  From IE work, I know that spinning up a canvas and creating the graphical context requires a bit of processing, and I wouldn't be surprised if this is costly on older iOS devices too.
