### ISSUE TITLE
Adding more params.

### ISSUE THREAD

**Issue by akshay1000** [akamai/boomerang#204]
How about adding more params to the beacon?..Is there any way using which I can get the number of requests served and the page weight ? Or calculate them using the basic available metrics being made available if possible similar to the reference image attached.
![inkedcapture_li](https://user-images.githubusercontent.com/15210683/41148112-ccdad756-6b25-11e8-862d-cc60ccce7745.jpg)

**Comment by bluesmoon** [comment]
Have you tried the ResourceTiming plugin?

**Comment by nicjansma** [comment]
Also note that capturing true Page Weight or matching what you see in dev tools is nearly impossible with ResourceTiming.  See https://nicj.net/resourcetiming-visibility-third-party-scripts-ads-and-page-weight/ for more details.
