### ISSUE TITLE
Clicks plugin fails to process config

### ISSUE THREAD

**Issue by sschnee** [akamai/boomerang#205]
Clicks plugin won't properly process configuration information passed to it because its initialization code passes a name to pluginConfig that doesn't match what it used when defining the plugin via BOOMR.plugins.Clicks = {....}  :

`	BOOMR.utils.pluginConfig(impl, config, "clicks", properties);`

So the trivial fix is to just capitalize the 'c' in the call above, but maybe a better solution would be to make the string match in both pluginConfig and main boomerang init function case independent?

**Comment by bluesmoon** [comment]
We wouldn't be able to enforce plugins that have names that differ only in case because javascript object names are case sensitive, and plugin authors do not have to "register" a plugin.

Fixing the case is the only option that would work.

**Comment by sschnee** [comment]
Good point.

**Comment by MartinNuc** [comment]
I think I encounted this issue. This is my first day playing with boomerang and I am wondering how to pass config to click plugin without modifying its source. Should I use lowercase name during `init()`?

```
    BOOMR.init({
      beacon_url: beaconUrl
      clicks: {
        click_url: beaconUrl
        onbeforeunload: true
      }
      instrument_xhr: true
      autorun: false
    })

```

**Comment by bluesmoon** [comment]
@andreas-marschke looks like this needs fixing

**Comment by nicjansma** [comment]
Fixed via https://github.com/akamai/boomerang/pull/219
