### ISSUE TITLE
Cannot get BW after cookie expire

### ISSUE THREAD

**Issue by rahulsahu47** [akamai/boomerang#213]
Hi., 

I am developing a web app where we need to check Bandwidth whenever we navigate to that page.
For that I reduced cookie_exp to 120, and we observed that cookie is expired after 120 sec but after that bandwith test is not running again. Can you please help us in that.

Thanks,
Rahul

**Comment by nicjansma** [comment]
Hi @rahulsahu47!  That seems like quite a short cookie expiration window, do you really want to re-run bandwidth tests on your users every 120 seconds?

Have you verified that after 120 seconds, the cookie is no longer in the browser?

Are you setting the `user_ip`?

Are you on HTTPS and have enabled `test_https`?

You can set a breakpoint [here](https://github.com/akamai/boomerang/blob/master/plugins/bw.js#L566) and see if the cookie is still fetched and what Boomerang does after it reads it.  Only if that function returns `false` do the bandwidth calculations run.

If none of those are obvious, please run a debug version of Boomerang and post the log from the browser console.

**Comment by nicjansma** [comment]
Please let us know if this issue persists for you.
