### ISSUE TITLE
undefined is not an object (evaluating 'screen.orientation.angle')

### ISSUE THREAD

**Issue by hakimelek** [akamai/boomerang#214]
Experiencing the following errors using the Continuity plugin in iPhone/iPad user agents:  

`TypeError: undefined is not an object (evaluating 'screen.orientation.angle')`

`Unable to get property 'angle' of undefined or null reference`

`Uncaught TypeError: Cannot read property 'angle' of undefined`

**Comment by querymetrics** [comment]
Thanks for mentioning the prefixed `screen.msOrientation` and `screen.mozOrientation`, I hadn't included those in my fix but it would help to support more browsers.

iOS doesn't support the Screen Orientation API, but it does support the deprecated `window.orientation` which will give us the orientation (see https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation).

**Comment by nicjansma** [comment]
Fixes via 8548072455afa0294068cec4e70b274d6cecd8d9 and  https://github.com/akamai/boomerang/pull/215
