### ISSUE TITLE
Does boomerang provide ability to measure upload speed?

### ISSUE THREAD

**Issue by aquacode** [akamai/boomerang#217]
What is the recommended way to test/measure a user's upload speed? 
Add a custom plugin? Has anyone done this already?

**Comment by bluesmoon** [comment]
I honestly do not think this is easily possible.  If this is a form POST that changes the base page, then the time would be the same as the load time of the subsequent page, and you'd take object size divided by this time to get upload throughput (not technically speed).

If this is XHR, then you'd be able to take the XHR load time instead (easiest to pull it out of the `onbeforebeacon` event).

You cannot, however, measure real time throughput by overloading these methods.  To do that, you'd have to use an XHR upload, and use the `onprogress` event.  You can reuse code from here: http://christopher5106.github.io/web/2015/12/13/HTML5-file-image-upload-and-resizing-javascript-with-progress-bar.html

We do not have a plugin to do this.

**Comment by aquacode** [comment]
Thanks for the response. Will have a look at the link you provided. Would you recommend we implement as a custom plugin? Why has the team elected to not create a plugin already for such a feature?

**Comment by bluesmoon** [comment]
We haven't elected not to create a plugin for this feature. It's more correct to say that there has been no request for this data.

**Comment by nicjansma** [comment]
@aquacode please let us know if you create a plugin!  Closing this in the meantime.
