### ISSUE TITLE
Some links on http://akamai.github.io/boomerang/ return a 404

### ISSUE THREAD

**Issue by andydavies** [akamai/boomerang#226]
Some of the links within the main documentation - http://akamai.github.io/boomerang/ - return a 404 as they link to https://soasta.github.io/ instead of akamai.github.io

**Comment by nicjansma** [comment]
Thanks @andydavies we had a fix for this but forgot to push to `gh-pages` https://github.com/akamai/boomerang/pull/208

**Comment by nicjansma** [comment]
Fixed now!
