### ISSUE TITLE
Question: What format does Boomerang log in?

### ISSUE THREAD

**Issue by davidfstr** [akamai/boomerang#228]
I am trying to collect real page & resource load metrics when users load my website. I am evaluating Boomerang for this purpose.

According to your [online documentation](https://akamai.github.io/boomerang/), Boomerang's logged data contains the following information:

* Page characteristics such as the URL and Referrer
* Overall page load times (via NavigationTiming if available)
* DNS, TCP, Request and Response timings (via NavigationTiming)
* Browser characteristics such as screen size, orientation, memory usage, visibility state
* DOM characteristics such as the number of nodes, HTML length, number of images, scripts, etc
* ResourceTiming data (to reconstruct the page's Waterfall)
* Bandwidth
* Mobile connection data
* DNS latency
* JavaScript Errors
* XMLHttpRequest instrumentation
* Third-Party analytics providers IDs
* Single Page App interactions

But what format is all that information captured in? I don't see an example of the output listed anywhere. Is it some kind of custom JSON or XML format? Is it something standard like [HAR](http://www.softwareishard.com/blog/har-12-spec/)?

If the output format is not a standard format then I would have to budget time to implement a visualizer for Boomerang's output format if I were to use Boomerang, since I don't see any such visualizer linked from the documentation pages.

P.S. A big +1 from me to fix #226 which makes it difficult to read online documentation for Boomerang.

**Comment by bluesmoon** [comment]
The data is sent as key value pairs on the query string or as post data. Basically the most primitive form of the common gateway interface. Each plugin documents the keys and values that it adds. 

As far as visualization tools go, there are a bunch of other open source projects that visualize tolerant data. We done maintain any of them though. 

Akamai also provides a commercial collection, visualization and analysis service for boomerang called mPulse that you can use.

**Comment by davidfstr** [comment]
Thanks for the reference to mPulse.

I shall continue my research.

**Comment by nicjansma** [comment]
An example plugin, where each lists the data it adds to the URL:

https://akamai.github.io/boomerang/BOOMR.plugins.RT.html#toc1__anchor
