### ISSUE TITLE
Minimum Frame Rate is measured per 0.1 second, instead of per 1 second

### ISSUE THREAD

**Issue by manofearth** [akamai/boomerang#234]
My opinion is that `c.f.m` value has unexpected meaning. It means "minimum frame rate **per 0.1 second**", while I expect "minimum frame rate **per 1 second**". It is because [COLLECTION_INTERVAL](https://github.com/akamai/boomerang/blob/master/plugins/continuity.js#L702) = 100 ms

**Comment by nicjansma** [comment]
Hi @manofearth!  That is true, since we wanted a small enough collection interval where we could show granular data, we picked a bucket size of 100ms, and `c.f.m` is based on that bucket size.

I've updated the documentation https://github.com/akamai/boomerang/pull/236 to reflect this.
