### ISSUE TITLE
Restiming data compression

### ISSUE THREAD

**Issue by sukrat-kashyap** [akamai/boomerang#235]
I would like to know the `*` being used in the `restiming.js`. I understand that the `|` are being used as separate entries. But I couldn't find the documentation for the usage of `*`. It would be nice if we could get the pseudo code of the decompressor.

@nicjansma Any help would be appreciated!

**Comment by bluesmoon** [comment]
You can see the code here: https://github.com/nicjansma/resourcetiming-compression.js/blob/master/src/resourcetiming-decompression.js

**Comment by sukrat-kashyap** [comment]
Thank you for the quick response. Appreciate that!

**Comment by aftabnaveed** [comment]
Is it possible to decompress the resource timings `ResourceTimingDecompression.decompressResources` in nodejs? Or how can I uncompress the data on the server-side? 
Sorry for commenting on a closed issue.

**Comment by bluesmoon** [comment]
@aftabnaveed yes, install the `resourcetiming-compression` package from npm or bower and use it as mentioned in the docs.
