### ISSUE TITLE
c_tti_hi should support background images

### ISSUE THREAD

**Issue by hakimelek** [akamai/boomerang#237]
Currently turning on hero-image detection to measure c_tti_hi works only on `img` elements, however we can make it detect css `background-image` on `div` elements as well. I can open a PR if that sounds interesting.

**Comment by nicjansma** [comment]
@hakimelek We'd love to see a PR for this, thanks!

**Comment by nicjansma** [comment]
Closing this out since https://github.com/akamai/boomerang/pull/251 was opened!
