### ISSUE TITLE
Web Worker Implementation

### ISSUE THREAD

**Issue by oravecz** [akamai/boomerang#240]
Has there been consideration of moving Boomerang to a Worker? Any issues to be considered if the plugins used did not reference the DOM?

**Comment by nicjansma** [comment]
As @bluesmoon mentions, I think _most_ of the plugins interact with the DOM, at least in some way.

We're definitely open to moving some Boomerang work to a worker if it makes sense, i.e. heavy-CPU or expensive methods.  As an example, one thought was to move ResourceTiming's compression work to a worker to [reduce its overhead](https://github.com/akamai/boomerang/issues/174), as it's one of the most expensive things Boomerang does, though we've recently addressed its computational cost significantly.

One downside of a worker is that you need the worker script (e.g. `new Worker('worker.js')`) that actually does the work, so the entire Boomerang build/deployment/etc would have to be updated to accommodate.  So we're not sure if Workers are worth the overhead for them right now.

We can re-open this issue if you have any specific scenarios you think a Worker would be helpful in!
