### ISSUE TITLE
Speed index plugin

### ISSUE THREAD

**Issue by abarre** [akamai/boomerang#241]
We added a [speed index plugin](https://github.com/fasterize/boomerang/blob/fasterize/plugins/speedindex.js) at Fasterize.
This is based on https://github.com/WPO-Foundation/RUM-SpeedIndex.

Even if this is completely different than synthetic Speed Index based on video processing, the approach follow in the script is interesting.

Do you have an interest in adding such a plugin in official boomerang script ? 

PS : we also see that dynatrace created a [RUM speed index](https://www.dynatrace.com/blog/visually-complete-speed-index-for-real-user-monitoring-rum/) metrics based on the mutationObserverAPI.

**Comment by bluesmoon** [comment]
We'd looked at adding RUM SpeedIndex a couple of years ago, but our tests showed that on pages with a lot of images it can lock up the browser for several minutes.  We'd definitely be interested if it does not have an impact on the user experience.

**Comment by nicjansma** [comment]
@abarre if you're interested in porting it over, we're always looking for contributions!

We'll need tests that cover the plugin.  Some documentation is here: https://akamai.github.io/boomerang/tutorial-tests.html, and we can help with any questions.  If you want to open the PR without tests that's fine too, though it may take us longer to write some tests and merge it in.

Closing this out and looking forward to a PR if you can!
