### ISSUE TITLE
Boomerang Use Strict compliance

### ISSUE THREAD

**Issue by quintenp** [akamai/boomerang#242]
Hi folks,

Are there any plans on getting the code strict mode compliant, there are a couple of glaring issues that needs to be solved to achieve this. 

Raising a pr for it would be straight forward however it would have to be maintained in all future requests, what is your stance here?

**Comment by nicjansma** [comment]
Hi @quintenp !

Due to our desired compatibility with older browsers such as IE6+, unfortunately we can't use strict mode.

Some additional details are in https://github.com/akamai/boomerang/issues/117.
