### ISSUE TITLE
Deprecation errors in Chrome 72

### ISSUE THREAD

**Issue by khalwat** [akamai/boomerang#244]
I have a custom build Boomerang beacon with the following plugins:

```
{
    "plugins": [
        "plugins/auto-xhr.js",
        "plugins/rt.js",
        "plugins/painttiming.js",
        "plugins/navtiming.js",
        "plugins/errors.js",
        "plugins/mq.js",
        "plugins/webperf-boomer-init.js"
    ]
}
```

...and I see the following deprecation warnings when it's loaded in Chrome 72:

```
boomerang-1.0.0.min.js?v=1549688134:13 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
done @ boomerang-1.0.0.min.js?v=1549688134:13
boomerang-1.0.0.min.js?v=1549688134:13 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
done @ boomerang-1.0.0.min.js?v=1549688134:13
boomerang-1.0.0.min.js?v=1549688134:13 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Paint Timing. https://www.chromestatus.com/features/5637885046816768.
```

Am I doing something wrong in the build, or will this need to be addressed in updates to Boomerang?

**Comment by nicjansma** [comment]
@khalwat Do you have these two fixes?

https://github.com/akamai/boomerang/commit/3418aea678822d66d4eda04a5de13de710b0209c#diff-02b41d33bc67108db45ab102c10df206
https://github.com/akamai/boomerang/commit/45c8ebc7feb985318a6c4a79661465b23366b32a#diff-02b41d33bc67108db45ab102c10df206

**Comment by judwhite** [comment]
@nicjansma I was just going to open an issue to ask if y'all would accept a PR for this fix. Thanks for the links!

**Comment by khalwat** [comment]
I don't think I do -- it looks like the latest release was tagged from back in November:

```
1.621.0
@nicjansma nicjansma released this on Nov 13, 2018 · 11 commits to master since this release
```

Should I be pulling from `dev-master` or such?

**Comment by khalwat** [comment]
Alright, so I'm a tad confused. My `package.json` has this version:

```
        "boomerangjs": "^1.621.0",
```

...which means I should indeed have these fixes in there.

**Comment by bluesmoon** [comment]
pull from master, a new release may not have been tagged.

**Comment by nicjansma** [comment]
@khalwat 1.621.0 should have the latest changes.  We may be missing an edge case where we still attempt to use `chrome.loadTimes()`.  Is this repro consistent?  Can you share a page we can look at?

**Comment by nicjansma** [comment]
We've found an edge-case that might trigger this warning, and have a fix being reviewed.

**Comment by nicjansma** [comment]
Fixed via https://github.com/akamai/boomerang/commit/207f868ce795c3cac6a35bb214d4a46d2342f10a
