### ISSUE TITLE
Why can't the monitored iframe send beacon?

### ISSUE THREAD

**Issue by yanfch** [akamai/boomerang#246]
Here is my usecase:

parent:
```
BOOMR.init({
  beacon_url: "http://xxxxxx/bomcrang",
  ResourceTiming: {
    enabled: true,
     clearOnBeacon: true
   },
   IFrameDelay: {
      enabled: true,
      monitoredCount: 1
    },
    autorun: false,
});
```
child
```
BOOMR.init({
  IFrameDelay: {
    enabled: true,
    registerParent: true
  }
})
```

![image](https://user-images.githubusercontent.com/10338055/52838262-fd546780-312c-11e9-879a-a8422a4c6187.png)

Why didn't the child page_load_beacon event trigger?

beacon are not sent

Any help?

**Comment by querymetrics** [comment]
@yanfch In the console logs you posted, the first line should be output by the child and the second should be output from the parent. The pageid (`wsiqrk1s`) is the same for both messages though which shouldn't happen.
Are there any more log lines?
Is your iframe dynamically added to the page? 
Do you have a public URL for a test page that we can look at?

**Comment by nicjansma** [comment]
@yanfch Please let us know if you still need help with this, and we can re-open the issue.
