### ISSUE TITLE
Removing variables doesn't stop beacon from being sent

### ISSUE THREAD

**Issue by vishalsingh98** [akamai/boomerang#249]
Even if all the variables are removed in before_beacon event, beacon is still sent out. Looking at the code, the problem seems to be related to following code in sendBeaconData:

(boomerang.js line 3412)
```
                        // Check that we have data to send
			if (data.length === 0) {
				return false;
			}
```

Given that data is an object, not an array (see declaration at line 3225: varsSent = {}), data.length is undefined and the condition will never be met (undefined === 0 will always return false).

**Comment by nicjansma** [comment]
Thanks @vishalsingh98 we've fixed this and will back-port the changes soon.
