### ISSUE TITLE
sendBeacon to use application/json 

### ISSUE THREAD

**Issue by zhouyu94** [akamai/boomerang#252]
hi, first of all. Thank you for implementing this plugin, which is very useful.
then , i want to kown how to fix sendBeaconData() function, You used three ways to report the data, but now it is easiest for me to parse the data when using XHR and setting the transmission format to json. 
After I tried to modify the code, I found that I could not customize the request header.
but i found this:
![image](https://user-images.githubusercontent.com/24785789/53854434-6fb9b880-4004-11e9-809c-6d394fbed9a5.png)
i comment out the three ways to send the original, i fix code is :
```
var client = new XMLHttpRequest();
 client.open("POST", impl.beacon_url, false);
client.setRequestHeader("Content-Type", "application/json");
client.send(JSON.stringify(data));
```
what should i do?

**Comment by nicjansma** [comment]
Hi @zhouyu94 .

It sounds like you may be able to modify and call the existing `sendXhrPostBeacon()`:

https://github.com/akamai/boomerang/blob/master/boomerang.js#L3541

`sendXhrPostBeacon()` is already doing most of what you have above, however:

* Please don't send synchronous XHRs (the third `false` argument to `client.open()`), as it will degrade and could hang the user experience
* If you're sending the `application/json` `Content-Type`, the request is no longer considered a "Simple Request", according to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests).  As a result, the request will do a "Pre-Flight" check to look for the CORS headers, such as `Access-Control-Allow-Origin`.  The [Pre-Flight](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests) will need to be satisfied before the JSON payload will be sent (as a second request).  That's likely what you're seeing with "Provisional Headers" above.
    * This is one of the reasons we use `application/x-www-form-urlencoded` -- it is compatible with Simple Requests, and doesn't require the extra Pre-Flight.

If you make these changes and want to open a Pull Request so others could send beacons as JSON, please do!
