### ISSUE TITLE
iOS Network Info 

### ISSUE THREAD

**Issue by zhouyu94** [akamai/boomerang#253]
when i use this plus, i found this, it dont get ios network info, like `effectiveType` or `type`. the boomerang do not support get ios network info?
@bluesmoon,@nicjansma

**Comment by bluesmoon** [comment]
Make sure you have the `mobile.js` plugin added.

**Comment by bluesmoon** [comment]
https://github.com/akamai/boomerang/blob/master/plugins/mobile.js

**Comment by zhouyu94** [comment]
yes, i add `mobile.js` into plugins

**Comment by bluesmoon** [comment]
iOS does not support that API. It's only available on Android devices.

**Comment by zhouyu94** [comment]
I also queried some information before, which is what you said. If this is the case, if i want to get IOS network related information, only rely on IOS native development to do this.    thanks your answer
