### ISSUE TITLE
Navigate away after beacon is sent

### ISSUE THREAD

**Issue by CACUser** [akamai/boomerang#255]
On the first page of the website I do a BW test. In the handler page for the beacon p the beacon_url, after storing the BW data, I would like to navigate to another page, using php - header('Location:' ....) function . I am able to store the data, but unable to navigate away from the beacon_url. Does the beacon send any headers after sending the header? if it is sending headers - then the php  header function to navigate to another page  will not work. 

Is there a way to access the  beacon url after it is created, but before it is sent?

from: sendBeaconData: function(data) 
url = impl.beacon_url + ((impl.beacon_url.indexOf("?") > -1) ? "&" : "?") + paramsJoined;

The url variable from above?

**Comment by nicjansma** [comment]
Hi @CACUser, I'm trying to understand the scenario here a bit more.

You're saying that:

1. After the bandwidth test is complete, Boomerang sends a beacon to something like `/beacon.php`
2. In `beacon.php`, you're using PHP's `header("Location: ...");` function to redirect the request

Is that correct?

Are you trying to redirect the _beacon_ or the _user_?  (2) above will only redirect the `beacon.php` _beacon_ response to another URL -- it won't navigate the _user_ to any other page or anything.

> Does the beacon send any headers after sending the header

Boomerang uses XHR, IMG or `sendBeacon()` to send the beacon data to your server.  It does not set any additional HTTP _Request_ headers beyond what the browser normally sends.

> if it is sending headers - then the php header function to navigate to another page will not work.

I think you're referring to the fact that PHP `header("Location: ...");` needs to come before any other PHP HTTP _Response_ headers being set.  That's all controlled by your PHP code, not from Boomerang or its beacon _Request_ HTTP headers.

If you're looking to redirect the _user_ after the beacon is sent, you can listen for the `beacon` event and navigate the user away by changing the `window.location`:

e.g.

```
BOOMR.subscribe("beacon", function() {
  window.location.href = "/myotherpage";
});
```

If I've misunderstood anything above, please let us know.

**Comment by nicjansma** [comment]
Closing this for now, please re-open if further clarification is needed.
