### ISSUE TITLE
Timed reporting

### ISSUE THREAD

**Issue by zhouyu94** [akamai/boomerang#263]
There is a scenario. When the mobile user uses his own traffic, the amount of data sent by the monitoring will be relatively large. At this time, can the data of a certain size be reported through the timing, and all the other data are discarded and not reported?
Does Boomerang have the ability to cache data and then periodically report data?

**Comment by andreas-marschke** [comment]
Boomerang only makes a distinction if it knows the URL would be over 2k chars and tries to POST in those circumstances. 

You can have a look at `boomerang.js` and the `real_sendBeacon()` function if there is anything for your case that you'd like to optimise.

**Comment by bluesmoon** [comment]
I guess another thing you can do is subscribe to the before_beacon event and remove items from the beacon that you consider not important.

**Comment by zhouyu94** [comment]
@bluesmoon I have thought of the way you said, but no matter how small the beacon is sent, it will take up the number of browsers sent. 
	
For example, if I need to get a lot of data interface data in one of my pages, I will have many requests. When each xhr request is monitored, the request from the browser will be doubled.This also means that I have no way to control the number of beacons sent, reducing the number of browsers sent by the beacon.

So I just thought about caching on the client side and further simplifying the beacon data, and then set it up, for example, 3m.

**Comment by zhouyu94** [comment]
@andreas-marschke What you said should be another situation, when the beacon data is too large.

Thank you for your answer
