### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by argovind** [akamai/boomerang#264]
HP Fortify scanner reported 3 high vulnerabilities in boomerang.js file. I am not sure, if this issue was already reported. Any suggestions / fix would be helpful. 

[Boomerang HP Fortify Vulnerability summary.docx](https://github.com/akamai/boomerang/files/3306397/Boomerang.HP.Fortify.Vulnerability.summary.docx)

Thanks

**Comment by bluesmoon** [comment]
Can you post the contents of the file? We prefer not to open untrusted word docs.

**Comment by bluesmoon** [comment]
These are false flags. They are just random ID generation that need to be somewhat random.  Boomerang doesn't do any security work and does not rely on unpredictability of random numbers.
