### ISSUE TITLE
Merge boomerange and custom object and then fire beacon

### ISSUE THREAD

**Issue by pankajmahesh** [akamai/boomerang#265]
hi,

Is there a way to intercept beacon fire from boomerang script and then fire single beacon with extra object merged?

thanks

**Comment by bluesmoon** [comment]
You need to write a boomerang plugin that adds data to the beacon.  You might also be able to do this by subscribing to `onbeforebeacon` and adding it there.

**Comment by pankajmahesh** [comment]
Hi,

I have created the wrapper which override send beacon but I see it sends 2-3 ajax request in network tab with different data values. How do I make it just single call?

Thanks,
Pankaj

**Comment by ashenoy2014** [comment]
@pankajmahesh Rather than overriding send beacon, it will be better to follow @bluesmoon advice and create a separate plugin that listens for `onbeforebeacon` event and adds the additional custom data that you need on the beacon via BOOMR.addVar. This should ensure only sending a single request with your additional data in the beacon.

**Comment by pankajmahesh** [comment]
@ashenoy2014 @bluesmoon 

Let me describe the issue, 

1. We want to add boomr object inside our object as key
2. We are overriding certain boomr object keys as per our DB schema
3. Currently there are multiple boomr hits on page with different set of data. How do i make it single and then fire beacon with our custom obj.

**Comment by nicjansma** [comment]
@pankajmahesh Boomerang may fire several beacons, depending on how your site is configured.  If you want to share a page with Boomerang on it, we can take a look.  Typically, Boomerang will send at least two beacons:

* Page Load
* Unload

Of course if you've configured XHR or SPA or Error monitoring, those can all send additional beacons as well.  The parameters on the beacon can help you differentiate what type of beacon it is.  Look for the `rt.start` and `http.initiator` and `rt.quit` parameters.  All of the parameters are described in the docs, e.g. for the [RT](https://akamai.github.io/boomerang/BOOMR.plugins.RT.html) plugin.

As the others have suggested, creating a plugin that listens for `beforebeacon` will give you the ability to `BOOMR.addVar()` before the beacon is sent.  `addVar()` will either set or overwrite existing data, so you can use that as an interception point.

**Comment by pankajmahesh** [comment]
Thanks

Thanks,
Pankaj
