### ISSUE TITLE
Remove beacon details from console

### ISSUE THREAD

**Issue by pratikgolchha** [akamai/boomerang#267]
Hi All,

I am using boomerang and boomerang is creating lots of console logs. Is there any way to stop it.

--Pratik

**Comment by bluesmoon** [comment]
See the documentation for the `log` config option.

**Comment by pratikgolchha** [comment]
Can you give me the link.

**Comment by bluesmoon** [comment]
https://developer.akamai.com/tools/boomerang/docs/BOOMR.html#.init__anchor

**Comment by nicjansma** [comment]
```
BOOMR.init({
  ...
  log:null,
  ...
}
```
