### ISSUE TITLE
Does Boomerang require the use of cookies and/or local storage?

### ISSUE THREAD

**Issue by ellenchristine** [akamai/boomerang#269]

**Comment by bluesmoon** [comment]
Not required, but boomerang's features are enhanced if it can set cookies.  See https://developer.akamai.com/tools/boomerang/docs/BOOMR.plugins.RT.html#toc2__anchor and https://developer.akamai.com/tools/boomerang/docs/BOOMR.plugins.BW.html#toc4__anchor

**Comment by ellenchristine** [comment]
Can we collect the following metrics without cookies/local storage?

 - Page load time
   - Geographical region
   - Browser/browser version

**Comment by bluesmoon** [comment]
Not geo location as boomerang does not collect that. Browser you can. Page
load time only in modern browsers.

**Comment by ellenchristine** [comment]
Thanks, really appreciate your response. What about IP?

**Comment by bluesmoon** [comment]
We also do not collect IP since that is not exposed at the browser level, however, since you most likely use TCP/IP at the lower levels of your network stack, you can retrieve the IP from those packet headers on the server.
