### ISSUE TITLE
Issues with fallback method in Boomerang loader snippet

### ISSUE THREAD

**Issue by kooroshloop** [akamai/boomerang#270]
My question is about the following Boomerang loader snippet:
https://developer.akamai.com/tools/boomerang/docs/tutorial-loader-snippet.html

The fallback iframe method (iframeLoader() function on line 44) for those browsers that don’t support the main method (link rel=“preload”), we see mixed results. In Firefox specifically, if there are a lot of other resources to load on the page, and inserting the iframe element happens before those resources finish loading, the loading of our script still blocks the loading of the page. But if our script is the only thing being loaded on the page, page load is not blocked.

**Comment by bluesmoon** [comment]
Can you post your code?

**Comment by kooroshloop** [comment]
@bluesmoon 

I've attached our version of the snippet. We've made some modifications to replace variable names, added logic to avoid double-loading of our script, and increase the preload timeout.

But the issue we're facing has to do with the iframe fallback method, specifically on line 75 in the bootstrap() function. Before our modification, the script was being added to the document body of the iframe. This doesn't work for us since some variables we declare need to be in the scope of the parent window. So we append the script element to the parent window.

This causes the un-blocking of the load event to stop working. It actually only works intermittently.

[script-loader.txt](https://github.com/akamai/boomerang/files/3597932/script-loader.txt)

**Comment by bluesmoon** [comment]
Yes, that is expected. You can only get the non blocking feature if you add
the script to the iframe after the iframe's onload event fires.

>
It is fairly easy to share variables between the iframe and the main window
using references since they run in the same security context.
