### ISSUE TITLE
BUG: rt.si not working as expected

### ISSUE THREAD

**Issue by sukrat-kashyap** [akamai/boomerang#273]
So, I was looking into the code. I don't know whether it's a feature or a bug. The problem we are facing now is that `rt.si` is updated to a new value on every page refresh. It doesn't have the same value for 30 minutes as expected. And the reason is below:

`Session.ID` gets a default value which is of the form `"qlcyu9i7o1"`
```
/**
* Session ID.  This will be randomly generated in the client but may
* be overwritten by the server if not set.
*
* @type {string}
*
* @memberof BOOMR.session
*/
ID: Math.random().toString(36).replace(/^0\./, ""),
```
Then in `RT.js` it gets set in the cookie:
```
// session ID
subcookies.si = BOOMR.session.ID;
```
But when next time when user refreshes the page because the format doesn't contain `-`: this code doesn't get executed and `BOOMR.session.ID` is not set and the default session ID that got generated is used.
```
if (subcookies.si && subcookies.si.match(/-/)) {
	BOOMR.session.ID = subcookies.si;
}
```
Also, this code adds the proper format. But it's too late until then as the cookie is already set without `-`
```
if (BOOMR.session.enabled) {
				impl.vars["rt.si"] = BOOMR.session.ID + "-" + Math.round(BOOMR.session.start / 1000).toString(36);
				impl.vars["rt.ss"] = BOOMR.session.start;
				impl.vars["rt.sl"] = BOOMR.session.length;
}
```

If you guys can confirm me it's a bug. I can probably raise a PR for the same.

**Comment by bluesmoon** [comment]
So this is something that's handled by a server-side module that sets BOOMR.session.ID via a config call to the server. I agree that the default is not very helpful without our custom module and has no usefulness with it, so probably best to change it out.

If you do choose to change it, I'd also recommend switching rt.si to a uuid rather than the random number string. We've seen a large number of collisions across users when using the current method.

**Comment by sukrat-kashyap** [comment]
Thank you for the quick response. Would 
you guys be okay if I raise a PR making the default value `generateuuid`, I think it will be helpful for everyone?

**Comment by bluesmoon** [comment]
Yes

>

**Comment by nicjansma** [comment]
Great find @sukrat-kashyap, yes a PR would be great

**Comment by sukrat-kashyap** [comment]
Thank you for merging! I will be closing this issue as this has been resolved.
