### ISSUE TITLE
Load plugins in an iframe

### ISSUE THREAD

**Issue by aftabnaveed** [akamai/boomerang#281]
With the more involved process (IFRAME) I can't find any reference to adding the plugins, how do I add plugins when BOOMR is loaded via an iframe?

**Comment by bluesmoon** [comment]
The same way you load plugins otherwise. The iframe didn't affect it.

**Comment by nicjansma** [comment]
The build process here can be used with loading Boomerang via the recommended Loader Snippet pattern or just `<script>` tags.

https://akamai.github.io/boomerang/tutorial-building.html
