### ISSUE TITLE
Boomerang Generates new session ID on each request

### ISSUE THREAD

**Issue by aftabnaveed** [akamai/boomerang#287]
I am having trouble to figure out why Boomerang is generating a new Session ID on each request or page refresh. Here is my config code. 

```jvascript
window.BOOMR.init({
  log: null,
  beacon_url: process.env.BEACON_ENDPOINT,
//   Errors: {
//       enabled: true,
//       // sendAfterOnload: true,
//       // sendInterval: 5000
//   },
  GUID: {
      cookieName: process.env.SESSION_COOKIE_NAME,
      //expires:
  },
  ResourceTiming: {
      enabled: true,
      clearOnBeacon: true
  }, 
  NavigationTiming: {
      enabled: true,
      clearOnBeacon: true
  },
  instrument_xhr: true,
  AutoXHR: {
    alwaysSendXhr: true,
    monitorFetch: true,
  },
  CustomEvents: {
    eventBeacon: process.env.BEACON_ENDPOINT,
  }
});
```

**Comment by nicjansma** [comment]
@aftabnaveed Session IDs are persisted by default in the `RT` cookie.  Is that cookie being set properly?

If not, you can use the "debug" build to see if there are problems setting the cookie.

You may need to set the `BOOMR.session.domain` if it's not the correct one.

**Comment by nicjansma** [comment]
Will close this for now, please comment if you still need help.
