### ISSUE TITLE
The cost of requestAnimationFrame

### ISSUE THREAD

**Issue by vzaidman** [akamai/boomerang#288]
Hello!

Monitoring FPS is a powerful indication of the smoothness of the user's experience, but how costly is it?

[From the official readme](http://akamai.github.io/boomerang/BOOMR.plugins.Continuity.html#toc5__anchor):

> Enabling Frame Rate monitoring should not have a noticeable effect on the page load experience. The frame callback may happen up to the device's refresh rate (which is often 60 FPS), and the work done in the callback should be barely visible in JavaScript CPU profiles (often less than 5ms over a page load).

But as far as I know, `requestAnimationFrame` generates a new animation frame when called, even if there is no need to generate it, which might slow down the user's experience (I'm not sure by how much).

Are you aware of any further information on this matter?

**Comment by nicjansma** [comment]
@vzaidman you're correct, there is certainly "work" being done when calling `requestAnimationFrame` in a loop even if no actual animation is happening.

When we profiled this in the past, on several sites, we didn't find much JavaScript CPU time being spent in the `requestAnimationFrame` callback -- that's where the 5ms number above comes from.

However there are probably other hidden costs like keeping the rendering engine more active, and I'm not sure if anyone has done research to quantify that.

What I would say is you should definitely consider if it's a whorthwhile metric for you to measure on your site.  You can do some profiles during load with it on and off to compare.  If it's not worthwhile, you can turn it off from `Continuity.monitorFrameRate=false`.

**Comment by vzaidman** [comment]
I encountered a case where at first everything was running smoothly until we had a loading animation outside of the screen or invisible because it was behind something (i can't recall exactly) and there each animation frame triggered an expensive re-paint.

So i believe this feature might be dangerous in some cases.

**Comment by nicjansma** [comment]
Good to know, and yeah there are probably a lot of edge-cases where it's expensive.  Good news is you can easily switch it off with `Continuity.monitorFrameRate=false`.  Let us know if you have any other concerns.
