### ISSUE TITLE
Deprecated prerender visibility state and firing prerender_to_visible

### ISSUE THREAD

**Issue by shoaibnawaz** [akamai/boomerang#290]
`document.visibilityState == prerender`
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState) confirms the deprication of this visibility state and my test confirms if this has been removed now.

My Test:
`BOOMR.utils.addListener(document, 'visibilitychange', function() { console.log(document.visibilityState); });`
This test prints either `hidden` or `visible` when tabs are toggled.

In boomerang.js `impl.fireEvent("prerender_to_visible");` is invoked for the [condition](https://github.com/akamai/boomerang/blob/c1d737a3456247ac6345f0f6cb180a96a398924a/boomerang.js#L2533) when page visibility state is changed from `prerender` to any other state.

So after the removal of prerender state, How should `BOOMR.plugins.RT.done()` be invoked in [rt.js#prerenderToVisible](https://github.com/akamai/boomerang/blob/c1d737a3456247ac6345f0f6cb180a96a398924a/plugins/rt.js#L1008)?

**Comment by bluesmoon** [comment]
That function will only be called on old browsers that still support the
feature. It is not required on newer browsers.

>
