### ISSUE TITLE
Installation Confusion...

### ISSUE THREAD

**Issue by cmdematos** [akamai/boomerang#294]
I have been reading the documentation. I have built and extracted the js but I don't have enough information on how to use this yet. The documentation references a beacon, some server-side resource but I dont understand whether the beacon is what is being measured or whether it is receiving posted information. There is also no documentation on how to implement the beacon on the server-side, assuming that is receiving information from boomerang, can we have a simple example of how to implement the server-side? What about integration with PIWIK/matomo or other servers that are supposed to receive this information?

The documentation omits all of this, it seems to be tribal information, like you I would know if I was grandfathered into this project by some beneficial happenstance.

Can someone please provide high level guidance beyond the HTTP javascript to be inserted and complete the picture on what happens when this information is posted...

**Comment by quintenp** [comment]
Beacon is simply a naming convention for the payload boomerang builds and sends to the server side. 

The payload or Beacon contains information gathered from the browser apis and specific plugins you have enabled.(Performance / Resources / Errors / W.e)

The server side implementation is up to you, it's a JSON payload at the end of the day with a bit of encoded fields and a lightweight compression, think there is a tri for resources as well. You could easily spin up an api and process it in which ever way your needs require, stick it into elastic or your storage of choice / visualize it with tools like kibana/splunk or build your own processing and visualization it's very open ended.

**Comment by bluesmoon** [comment]
Sorry, there used to be howto documents for what to do on the server-side. They should still be in git history in the gh-pages branch.

**Comment by bluesmoon** [comment]
Here you go: https://github.com/akamai/boomerang/blob/85aaefd75fde522c0ef895c4b22ad8a9a47ae968/doc/howtos/howto-read-data-from-a-beacon.md

**Comment by mc-chaos** [comment]
You could usw the inspectit ocelot eum Server(1) to receive the beacons and Export the to influxdb vor Prometheus. There will be a opentelemetry Plugin(2), too. You could than Tracey Form your users Browser.

1. https://inspectit.github.io/inspectit-ocelot/docs/next/enduser-monitoring/enduser-monitoring-server
2. https://github.com/NovatecConsulting/boomerang-opentelemetry-plugin

**Comment by mc-chaos** [comment]
There is a other new and active Projekt to receive beacons.
https://github.com/basicrum/backoffice

**Comment by nicjansma** [comment]
The current tutorial at https://akamai.github.io/boomerang/tutorial-howto-read-data-from-a-beacon.html covers some of this, but it would be worthwhile to update the `Backend Servers` section with more recent implementations.

**Comment by nicjansma** [comment]
Here's some additional links we know of right now

There are several open-source projects that can receive and analyze Boomerang data:

* [boomcatch](http://cruft.io/posts/introducing-boomcatch/)
* [boomerang-express](https://github.com/andreas-marschke/boomerang-express)
* [PIWIK](https://piwik.org/)
* [Backoffice of Basic RUM](https://github.com/basicrum/backoffice)
* [Boomerang Beacon Catcher of Basic RUM](https://github.com/basicrum/boomerang-beacon-catcher)
* [Boomerang-OpenTelemetry Plugin](https://github.com/NovatecConsulting/boomerang-opentelemetry-plugin)
* [Boomerang Drupal Module](https://www.drupal.org/project/boomerang)
* [Boomerang OpenACS plugin](https://openacs.org/xowiki/boomerang)

Here are some articles for putting it all together:

* [A Low Cost Performance Monitoring Setup with Boomerang, Boomcatch, and Datadog](https://www.tollmanz.com/rum-monitoring-boomerang-boomcatch-datadog/])
* [End User Monitoring with Ocelot](https://inspectit.github.io/inspectit-ocelot/docs/enduser-monitoring/enduser-monitoring-server)
* [Real User Monitoring using Boomerang, Boomcatch, StatsD, and Graphite — Setup guide](https://medium.com/@sunitj/real-user-measurement-using-boomerang-boomcatch-statsd-and-graphite-setup-guide-a2f60b5cb082)

We'll update the documentation with those soon.
