### ISSUE TITLE
Is the error plugin supports failure in CDN and promise rejection

### ISSUE THREAD

**Issue by tridev87** [akamai/boomerang#295]
1. I tried the promise rejection scenario and it is working. May be I am missing some configuration.
2. Does this support CDN failures. If I am loading a file dynamically and it gives 404. Here also it did not work for me.

**Comment by querymetrics** [comment]
@tridev87 The error reporting for promise rejection is only for unhandled errors. I'm assuming you're using the Fetch API, are you catching the 404 error in your code? Do you have a sample page?

**Comment by nicjansma** [comment]
@tridev87 The Errors plugin will only have visibility into XHR and fetch errors (non-2xx responses), if the `AutoXHR` plugin is also enabled and monitoring those.

Unfortunately we don't have visibility into other resource errors, as ResourceTiming doesn't give us those details.

Please let us know if you have a sample page we can debug with.

**Comment by nicjansma** [comment]
Closing, feel free to comment if more clarification is needed!
