### ISSUE TITLE
What can cause the timeline lengths to be different?

### ISSUE THREAD

**Issue by SeanWhipple** [akamai/boomerang#298]
I have been unable to reproduce this locally but we're capturing a lot of beacons from a client site and I'm noticing some beacons that have two timelines but of different length

Here is some data from a beacon that was captured on `Chrome`
### Frame Rate
```
Compressed: 0*h*02251*s*0356662
Uncompressed: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 5, 6, 6, 6, 2]
```

### Long Task
```
Compressed: 001
Uncompressed: [0, 1]
```

Why are there so few data points for the long task timeline?

**Comment by nicjansma** [comment]
@SeanWhipple I believe in this case, both timelines start at the same point (t=0).  FrameRate has a steady stream of data throughout the page load, but there is only a single LongTask detected (at the second bucket, 100ms-200ms).

The timeline data [trims any trailing "0"s](https://github.com/akamai/boomerang/blob/master/plugins/continuity.js#L906-L950), so you can assume after that LongTask at ~100-200ms that there weren't any following ones.

**Comment by nicjansma** [comment]
Closing, feel free to comment if more clarification is needed!
