### ISSUE TITLE
How can I use boomerang JS downloaded from NPM install? On the Vue page, you will always prompt undefined

### ISSUE THREAD

**Issue by yuanbwhub** [akamai/boomerang#299]
This is the browser's error log
```
main.js?56d7:21 Uncaught TypeError: Cannot read property 'init' of undefined
    at eval (main.js?56d7:21)
    at Module../src/main.js (app.js:1603)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at Object.1 (app.js:1737)
    at __webpack_require__ (app.js:791)
    at checkDeferredModules (app.js:46)
    at app.js:931
    at app.js:934
```
This is my code snippet
```
import BOOMER from 'boomerangjs/boomerang'

BOOMER.BOOMR.init({
  autorun: false
})
```
Please help me, thank you

**Comment by bluesmoon** [comment]
I'm not familiar with Vue, so can't comment on that, but we don't have anything called `BOOMER` in our code.  Our global is called `BOOMR` and it is set on the window object, so you'd just call `BOOMR.init`

**Comment by sukratkashyap** [comment]
@yuanbwhub If you are using Nuxt.js, you can do the following in your `nuxt.config.js`. Since, boomerang collects metrics from client-side, you can't really run it on server-side. Also, you will have to build boomerang to be able to use it with the plugins you are interested in. My recommendation would be to build boomerang separately and copy and paste the file in your `static` directory and refer it from there. (It's not the ideal way definetly, but this is as far as I know)
```
    plugins: [
        { src: '../node_modules/boomerangjs/boomerang.js', mode: 'client' }
    ]
```

**Comment by yuanbwhub** [comment]
> I'm not familiar with Vue, so can't comment on that, but we don't have anything called `BOOMER` in our code. Our global is called `BOOMR` and it is set on the window object, so you'd just call `BOOMR.init`

thanks very much , my mistake

**Comment by yuanbwhub** [comment]
If I want to monitor vue.js Do you have any good suggestions, such as which plug-ins should be introduced? Because I haven't found a plug-in suitable for Vue, only Angular.js. I really need your help , thanks.

**Comment by bluesmoon** [comment]
generally you should not need a separate plugin. The auto-xhr handler should work with any framework.

**Comment by nicjansma** [comment]
We also have build documentation here: https://akamai.github.io/boomerang/tutorial-building.html

Please let us know if you need anything clarified.
