### ISSUE TITLE
RT and SPA load order

### ISSUE THREAD

**Issue by mzheng15** [akamai/boomerang#303]
I currently have my plugins loaded in this order: XHR, SPA, History. does it matter if I load RT before or after these three?

**Comment by nicjansma** [comment]
@mzheng15 I would generally recommend the order in this file, excluding any plugins you don't need: https://github.com/akamai/boomerang/blob/master/plugins.json

That's what works for the builds we create for mPulse.

That would leave you with:

* `AutoXHR`
* `SPA`
* `History`
* `RT`

Each plugin should list any it depends on in the header doc.  The only hard dependency is AutoXHR -> SPA -> History (in that order).  RT could probably go before or after those.
