### ISSUE TITLE
is it posible include  client-IP or client-hostname in beacon

### ISSUE THREAD

**Issue by mc-chaos** [akamai/boomerang#312]
We have some performance issues with some browser-settings. We have already included boomerang.js in the (internal-) website an receiving the beacons for the site. We need a simple way to make a a/b Testing with different client-/browser settings. My idee was to select the client, with the changed settings and review the website performance for different tasks.

Is there a simple way to include the IP or hostname from the browser in the beacon?
Regards, Sascha

**Comment by bluesmoon** [comment]
The client IP is already included in the TCP/IP headers. You can read it server side using whatever function your back end language supports for that.

**Comment by mc-chaos** [comment]
Hi @bluesmoon , 
thx for your replay. I know, that the ip is in the tcp/ip header and that this could be read by the backend server. But i am looking for a solution without modifying the backend server. To modify the backend server (inspect-IT EUM Receiver) i need to wait for a release and so on and so on. A field at the beacon could be read with some config changes, without a release.  I am searching for a quick solution. If there is no way, i need to go the long way with a release of the backend server.
Regards Sascha

**Comment by bluesmoon** [comment]
The IP is not available to JavaScript. You can either read it when the beacon comes in, or you can add it to the HTML page when the page is generated, but both solutions require you to change the server.

**Comment by mc-chaos** [comment]
thx for the Information.
