### ISSUE TITLE
Latest releases not available in NPM or on Github

### ISSUE THREAD

**Issue by wmock561** [akamai/boomerang#320]
The 1.720.0 release of boomerang is available via NPM, but is not available here on Github. Also, the new 1.725.0 release (https://developer.akamai.com/tools/boomerang/release-notes) is not available on NPM or via Github.

https://github.com/akamai/boomerang/releases
https://www.npmjs.com/package/boomerangjs

**Comment by ceckoslab** [comment]
Hello @wmock561 

We are behind schedule with our quarterly open-source backport. I can't promise when we will do the backport and add 1.725.0 to NPM?

Is there something specific that you are look for in version 1.725.0?

Have a nice day.

**Comment by querymetrics** [comment]
The release notes in this repo are out of date but the`master` branch is at `1.720.0`.
See https://github.com/akamai/boomerang/blob/master/package.json#L3

**Comment by scottgifford** [comment]
> Is there something specific that you are look for in version 1.725.0?

Hey, I'm a colleague of @wmock561 , we are looking for the AutoXHR changes specifically.  We are just starting to add AutoXHR instrumentation to our site, and want to avoid running into issues/bugs that have already been fixed in 1.725.0.  In particular, from the [1.725.0 release notes](https://developer.akamai.com/tools/boomerang/release-notes#1.725.0-(november-3,-2020)):
> #### Breaking Changes
> * Boomerang will no longer send an “XHR Beacon” when an XMLHttpRequest does not result in any interesting DOM modifications (i.e. no new images, stylesheets, IFRAMEs or other XHRs were added). This change can be reverted to the previous behavior (of still sending an XHR Beacon) by setting the AutoXHR.xhrRequireChanges=false flag.
> #### Bug Fixes
> * Issue 868: AutoXHR: Don’t send XHR beacons if there were no DOM mutations
> * Issue 1081: AutoXHR: Don’t wait on lazy-loaded images
> * Issue 1079: AutoXHR: For XHR beacons that happen before Page Load, ResourceTiming data is properly added to the XHR beacon when it is fired

**Comment by nicjansma** [comment]
@scottgifford we generally try to do 2 or 3 backports to the OS repo a year.  We're due for another one shortly!

**Comment by nicjansma** [comment]
https://github.com/akamai/boomerang/pull/325 has the changes mentioned above.   We'll review and fix test failures and get it released on NPM shortly.

**Comment by nicjansma** [comment]
Published `1.737.0` on NPM: https://www.npmjs.com/package/boomerangjs/v/1.737.0
