### ISSUE TITLE
Publish Latest Boomerang Updates

### ISSUE THREAD

**Issue by xjamundx** [akamai/boomerang#323]
Are you planning to include the source for the latest version of boomerang mentioned here:
https://developer.akamai.com/tools/boomerang/release-notes/#mpulse-boomerang-release-notes

`1.737.0`

**Comment by nicjansma** [comment]
@xjamundx Yes!  We'll be doing a backport shortly (some additional details in https://github.com/akamai/boomerang/issues/320)
