### ISSUE TITLE
Can we use Boomerang to send custom metrics/logs?

### ISSUE THREAD

**Issue by hchhabada** [akamai/boomerang#330]
I want to use BOOM.sendMetric() to send custom metrics on the fly , use case is to send info logs https://developer.akamai.com/tools/boomerang/docs/BOOMR.html#.sendMetric__anchor
but when I try to use it gives an error saying sendMetric is not a function, I checked the open-source code, I could not find that function
https://github.com/akamai/boomerang/blob/master/boomerang.js
Is there any other way I can send logs/custom metrics?

**Comment by andreas-marschke** [comment]
`sendMetric` is a function we use for our commercial product [mPulse](https://www.akamai.com/de/products/mpulse-real-user-monitoring).

If your intend is frontend logging and you're using your own beacon collection infrastructure, you can always craft your own beacon by adding new variables and values to a beacon by way of `BOOMR.addVar`. Keep in mind you can always call sendBeacon but make sure your beacon is set up correctly. 

Review:
 - [boomerang.js: `sendBeacon()`](https://github.com/akamai/boomerang/blob/master/boomerang.js#L3925)
 - [boomerang.js: `real_sendBeacon`](https://github.com/akamai/boomerang/blob/master/boomerang.js#L3988)

This will give you a good idea for what will be able to be sent as a beacon.

An avenue you could go down would be creating your own "beacon_type" so to speak by setting `http.initiator`.
