### ISSUE TITLE
How does the Cache-Reload Plugin works

### ISSUE THREAD

**Issue by mc-chaos** [akamai/boomerang#332]
Hi,
i would find out how the "cache-reload" Plugin works. The links to the Blogposts are not up any more.
[BOOMR.plugins.CACHE_RELOAD](https://akamai.github.io/boomerang/BOOMR.plugins.CACHE_RELOAD.html)

Old links, with are note available any more.

        http://www.lognormal.com/blog/2012/06/05/updating-cached-boomerang/
        http://www.lognormal.com/blog/2012/06/17/more-on-updating-boomerang/

Regards, Sascha

**Comment by mc-chaos** [comment]
Hi @nicjansma , could you help anxd explane? 

Regards Sascha

**Comment by josebolos** [comment]
@mc-chaos Both links are available on the Wayback Machine:

https://web.archive.org/web/20180623101550/http://www.lognormal.com/blog/2012/06/05/updating-cached-boomerang/
https://web.archive.org/web/20180717021622/http://www.lognormal.com/blog/2012/06/17/more-on-updating-boomerang/

**Comment by nicjansma** [comment]
I'll take a stab at incorporating the text of those blog posts into the plugins's documentation soon.
