### ISSUE TITLE
API Key Disclosure

### ISSUE THREAD

**Issue by niyosh** [akamai/boomerang#334]
Is there any security issue to reveal "window.BOOMR_API_key" publically?

 <script>!function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if("False"=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="APIKEYHEAR",fun.....

**Comment by bluesmoon** [comment]
No. API key is not a secret.

**Comment by niyosh** [comment]
Thanks.
