### ISSUE TITLE
Integrate Plugins into asynchronous loader snippet

### ISSUE THREAD

**Issue by MariusBrill** [akamai/boomerang#336]
Hi everyone,

i would like to integrate plugins into boomerang loaded with the asynchronous loader snippet (the one using iframes). Do you have any example on how i can do this?

Best regards,
Marius

**Comment by ceckoslab** [comment]
Hello @MariusBrill 

Our readme is kind of long but somewhere in the middle we have documented the asynchronous loader snippethttps://github.com/akamai/boomerang/blob/master/README.md

We have the full source code and a minified version in the readme.

Does this work for you?

**Comment by bluesmoon** [comment]
Specifically if you want to add plugins, you need to run the build script with your plugins, that will create a single minified file that you use with the loader.

Note that it is no longer recommended to use the `iframe` loader as that is for legacy browsers.  Use the `link rel=preload` loader which falls back to iframe for older browsers.

**Comment by ceckoslab** [comment]
@MariusBrill here is also a tutorial about building Boomerang: https://akamai.github.io/boomerang/akamai/tutorial-building.html

**Comment by MariusBrill** [comment]
Hey guys,
Sorry for my late reply! Just saw the ticket again and saw that I didn't answer.
@ceckoslab the tutorial helped me a lot! Thank you so much :)

**Comment by SaschaBrechmannVHV** [comment]
@MariusBrill : Could this closed?
