### ISSUE TITLE
I am getting metrics in web page but I need to use a plugin and send it to opentelemetry collector how to do that

### ISSUE THREAD

**Issue by Akshayaad** [akamai/boomerang#355]

**Comment by bluesmoon** [comment]
Your best bet is to write a function that attaches to the `onBoomerangBeacon` or `onBeforeBoomerangBeacon` (these are custom events in the browser). That function will get an object with all the data that is to be sent, and then you format it for open telemetry and send it to your collector.

**Comment by mc-chaos** [comment]
Hi @Akshayaad ,
You could use this Plugin:
[OT-Plugin](https://github.com/NovatecConsulting/boomerang-opentelemetry-plugin)
Regards Sascha

**Comment by bluesmoon** [comment]
@mc-chaos that's pretty cool

**Comment by Akshayaad** [comment]
should we just add our opentelemetry endpoint here . Is there any demo PR it would be helpful
