### ISSUE TITLE
Any chance we can have a new release?

### ISSUE THREAD

**Issue by marclaporte** [akamai/boomerang#357]
The last release is 1.737.0 (Apr 16, 2021) by @nicjansma

And there are loads of enhancements as part of:
https://github.com/akamai/boomerang/pull/350

Thanks!

**Comment by bluesmoon** [comment]
Hi @marclaporte, 
The releases from the github page are just a tarball of the entire git repository. I wouldn't worry too much about an "official" release. Just fetch the latest git code and build from there.

**Comment by marclaporte** [comment]
Hi @bluesmoon!

I see what you mean.

Here is the context: We use boomerang as part of the Open Source project _Tiki Wiki CMS Groupware_: https://doc.tiki.org/Real-User-Measurement

As of now, we get version 1.737.0 via:
https://asset-packagist.org/package/npm-asset/boomerangjs

We could figure out a way to get the code from master. But we try as much as possible to use stable releases.

Thanks!

**Comment by bluesmoon** [comment]
I see. We'll have to discuss this internally as the version pushed to npm needs more maintenance than makes sense for us. We do not use the npm version internally, so it requires more testing and keeping track of upstream dependencies.

**Comment by marclaporte** [comment]
Even more code: https://github.com/akamai/boomerang/pull/359

**Comment by nicjansma** [comment]
Hi @marclaporte!  Once the team reviews the backport code, I'll make sure to publish a new NPM release.

**Comment by nicjansma** [comment]
Merged and published at 1.815.0!

```$ npm publish
npm warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm warn publish errors corrected:
npm warn publish scripts entry "bower-install" was fixed to remove node_modules/.bin reference
npm warn publish scripts entry "webdriver-manager-update" was fixed to remove node_modules/.bin reference
npm warn publish "repository.url" was normalized to "git+https://github.com/akamai/boomerang.git"
npm notice
npm notice 📦  boomerangjs@1.815.0
npm notice Tarball Contents
npm notice 131B .dockerignore
npm notice 168B .markdownlint.json
npm notice 4B .nvmrc
npm notice 413B .vscode/settings.json
npm notice 47.0kB Gruntfile.js
npm notice 1.7kB LICENSE.txt
npm notice 19.8kB README.md
npm notice 163.2kB boomerang.js
npm notice 1.5kB bower.json
npm notice 8.7kB doc/building.md
npm notice 1.4kB doc/contributing.md
npm notice 1.7kB doc/creating-plugins.md
npm notice 2.5kB doc/header-snippets.md
npm notice 0B doc/howtos.md
npm notice 1.4kB doc/howtos/howto-add-additional-timers-to-the-beacon.md
npm notice 1.5kB doc/howtos/howto-add-arbitrary-data-to-the-beacon.md
npm notice 1.0kB doc/howtos/howto-delay-page-load-time.md
npm notice 1.7kB doc/howtos/howto-measure-arbitrary-events.md
npm notice 12.7kB doc/howtos/howto-opt-out-or-opt-in.md
npm notice 6.8kB doc/howtos/howto-read-data-from-a-beacon.md
npm notice 2.0kB doc/howtos/howto-resourcetiming-buffer.md
npm notice 5.2kB doc/loader-snippet.md
npm notice 2.5kB doc/methodology.md
npm notice 3.0kB doc/page-overrides.md
npm notice 1.5kB doc/perf-tests.md
npm notice 11.8kB doc/README.template.md
npm notice 3.8kB doc/tests.md
npm notice 1.2kB doc/tutorials.json
npm notice 39.0kB doc/version-history.md
npm notice 363B lib/banner.txt
npm notice 5.9kB package.json
npm notice 5.6kB plugins.json
npm notice 109.6kB plugins/auto-xhr.js
npm notice 9.2kB plugins/bfcache.js
npm notice 28.7kB plugins/bw.js
npm notice 2.9kB plugins/cache-reload.js
npm notice 3.4kB plugins/cache-test-plugin.js
npm notice 5.5kB plugins/clicks.js
npm notice 6.6kB plugins/compression.js
npm notice 9.0kB plugins/consent-inlined-plugin.js
npm notice 139.1kB plugins/continuity.js
npm notice 4.8kB plugins/dns.js
npm notice 5.8kB plugins/early.js
npm notice 76.9kB plugins/errors.js
npm notice 18.1kB plugins/eventtiming.js
npm notice 2.2kB plugins/guid.js
npm notice 17.7kB plugins/history.js
npm notice 10.8kB plugins/iframe-delay.js
npm notice 6.5kB plugins/ipv6.js
npm notice 13.9kB plugins/memory.js
npm notice 2.7kB plugins/mobile.js
npm notice 3.6kB plugins/mq.js
npm notice 18.3kB plugins/navtiming.js
npm notice 15.1kB plugins/painttiming.js
npm notice 63.3kB plugins/restiming.js
npm notice 67.8kB plugins/rt.js
npm notice 24.8kB plugins/spa.js
npm notice 18.2kB plugins/third-party-analytics.js
npm notice 9.5kB plugins/usertiming.js
npm notice 91B plugins/zzz-last-plugin.js
npm notice 4.1kB snippets/autoxhr-snippet.js
npm notice 568B snippets/continuity-snippet.js
npm notice 1.9kB snippets/errors-snippet.js
npm notice 6.7kB snippets/loader-snippet-after-onload.js
npm notice 6.5kB snippets/loader-snippet.js
npm notice Tarball Details
npm notice name: boomerangjs
npm notice version: 1.815.0
npm notice filename: boomerangjs-1.815.0.tgz
npm notice package size: 269.6 kB
npm notice unpacked size: 1.1 MB
npm notice shasum: fee891778f126b61ffbcee38633888b3a2745106
npm notice integrity: sha512-U0biz1wd91m6j[...]VNaYbLD+rb3Rg==
npm notice total files: 65
npm notice
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
Authenticate your account at:
[redacted]
Press ENTER to open in the browser...

+ boomerangjs@1.815.0```

**Comment by francksefu** [comment]
Hello,
Thank you for adding BoomerangJS to npm, but here is what I get when I run: npm i boomerangjs

npm error code 127
npm error path /Applications/MAMP/htdocs/Orphelina/node_modules/boomerangjs

npm error command failed
npm error command sh -c npm run bower-install && npm run webdriver-manager-update
npm error > boomerangjs@1.815.0 bower-install
npm error > ./node_modules/.bin/bower install
npm error sh: ./node_modules/.bin/bower: No such file or directory
npm error A complete log of this run can be found in: /Users/francksefu/.npm/_logs/2024-10-10T10_32_49_559Z-debug-0.log
![Screen Shot 2024-10-10 at 12 40 33](https://github.com/user-attachments/assets/5ec673ef-0c71-424e-9677-2418a563636d)

**Comment by marclaporte** [comment]
@nicjansma can you reopen this task or should I create a new task with respect to an NPM release?

Thanks!

**Comment by marclaporte** [comment]
@bluesmoon @nicjansma 

So Bower will always be a dependency to install via NPM?

Thanks!

**Comment by marclaporte** [comment]
@nicjansma 
https://github.com/akamai/boomerang/releases is still at 1.737.0
https://asset-packagist.org/package/bower-asset/boomerang is still at 1.737.0

Thanks!

**Comment by marclaporte** [comment]
For the record, we are still at 1.737.0 here:
- https://github.com/akamai/boomerang/releases
- https://github.com/akamai/boomerang/tags

But we can get 1.815.0 from https://asset-packagist.org/package/npm-asset/boomerangjs

**Comment by nicjansma** [comment]
Sorry about that, I hadn't seen the updates in this Issue.

I've published 1.815.1 to NPM to get past the `npm install boomerangjs` failure.

```
$ npm install boomerangjs

added 6 packages in 946ms
```

I've published a release for 1.815.0 and 1.1815.1 in tag and releases:

* https://github.com/akamai/boomerang/releases/tag/1.815.0
* https://github.com/akamai/boomerang/releases/tag/1.815.1

**Comment by marclaporte** [comment]
@nicjansma @francksefu 

Thank you for this. We will try again to get package via NPM instead of https://asset-packagist.org/package/npm-asset/boomerangjs

I hope Bower is no longer a dependency.

**Comment by marclaporte** [comment]
It's looking good so far! https://gitlab.com/tikiwiki/tiki/-/merge_requests/8321
